/**
 * Station names data for English-Korean mapping
 * Converted from station-names.json for Vercel compatibility
 */

export const stationNames = {
  englishToKorean: {
    "Seoul Station": "서울역",
    "Seoul Stn": "서울역",
    "City Hall": "시청",
    "Jonggak": "종각",
    "Jongno 3-ga": "종로3가",
    "Jongno 5-ga": "종로5가",
    "Dongdaemun": "동대문",
    "Cheongnyangni": "청량리",
    "Yongsan": "용산",
    "Noryangjin": "노량진",
    "Yeongdeungpo": "영등포",
    "Guro": "구로",
    "Incheon": "인천",
    "Bupyeong": "부평",
    "Suwon": "수원",
    "Gangnam": "강남",
    "Yeoksam": "역삼",
    "Samseong": "삼성",
    "Samsung": "삼성",
    "Coex": "삼성",
    "Jamsil": "잠실",
    "Lotte World": "잠실",
    "Sindorim": "신도림",
    "Hongdae (Hongik Univ.)": "홍대입구",
    "Hongdae": "홍대입구",
    "Hongik Univ.": "홍대입구",
    "Hongik University": "홍대입구",
    "Hongik Uni": "홍대입구",
    "Hongik": "홍대입구",
    "Hapjeong": "합정",
    "Dangsan": "당산",
    "Yeouido": "여의도",
    "Konkuk Univ.": "건대입구",
    "Konkuk University": "건대입구",
    "KU": "건대입구",
    "Korea University": "고려대",
    "Seolleung": "선릉",
    "Sports Complex": "종합운동장",
    "Gangbyeon": "강변",
    "Ttukseom": "뚝섬",
    "Seongsu": "성수",
    "Wangsimni": "왕십리",
    "Euljiro 3-ga": "을지로3가",
    "Euljiro 1-ga": "을지로입구",
    "Chungjeongno": "충정로",
    "Ewha Womans Univ.": "이대",
    "Ewha Univ": "이대",
    "Ewha": "이대",
    "Sinchon": "신촌",
    "Sadang": "사당",
    "Nakseongdae": "낙성대",
    "Seoul Nat'l Univ.": "서울대입구",
    "Seoul National University": "서울대입구",
    "SNU": "서울대입구",
    "Guro Digital Complex": "구로디지털단지",
    "Mullae": "문래",
    "Gyeongbokgung": "경복궁",
    "Gyeongbok Palace": "경복궁",
    "Anguk": "안국",
    "Changdeok Palace": "안국",
    "Chungmuro": "충무로",
    "Dongguk Univ.": "동대입구",
    "Yaksu": "약수",
    "Apgujeong": "압구정",
    "Sinsa": "신사",
    "Express Bus Terminal": "고속터미널",
    "Express Terminal": "고속터미널",
    "Express Bus": "고속터미널",
    "Gyodae": "교대",
    "Nambu Bus Terminal": "남부터미널",
    "Yangjae": "양재",
    "Daehwa": "대화",
    "Juyeop": "주엽",
    "Myeongdong": "명동",
    "N Seoul Tower": "명동",
    "Namsan": "명동",
    "Hoehyeon": "회현",
    "Sookmyung Women's Univ.": "숙대입구",
    "Dongdaemun History & Culture Park": "동대문역사문화공원",
    "Hyehwa": "혜화",
    "Hansung Univ.": "한성대입구",
    "Mia": "미아",
    "Mia Sageori": "미아사거리",
    "Gireum": "길음",
    "Chongshin Univ.": "총신대입구",
    "Gwanghwamun": "광화문",
    "Cheonggu": "청구",
    "Haengdang": "행당",
    "Yeouinaru": "여의나루",
    "Mapo": "마포",
    "Gongdeok": "공덕",
    "Gimpo Airport": "김포공항",
    "Gimpo": "김포공항",
    "Banghwa": "방화",
    "Itaewon": "이태원",
    "Samgakji": "삼각지",
    "Noksapyeong": "녹사평",
    "Hangang": "한강진",
    "Sangsu": "상수",
    "World Cup Stadium": "월드컵경기장",
    "Digital Media City": "디지털미디어시티",
    "DMC": "디지털미디어시티",
    "Gangnam-gu Office": "강남구청",
    "Cheongdam": "청담",
    "Children's Grand Park": "어린이대공원",
    "Junggok": "중곡",
    "Ttukseom Resort": "뚝섬유원지",
    "Nonhyeon": "논현",
    "Hakdong": "학동",
    "Bogwang": "보광",
    "Jangam": "장암",
    "Dobongsan": "도봉산",
    "Mongchontoseong": "몽촌토성",
    "Gangdong-gu Office": "강동구청",
    "Cheonho": "천호",
    "Bokjeong": "복정",
    "Sanseong": "산성",
    "Moran": "모란",
    "Amsa": "암사",
    "Sinnonhyeon": "신논현",
    "Dongjak": "동작",
    "National Assembly": "국회의사당",
    "Yeomchang": "염창",
    "Gaehwa": "개화",
    "Olympic Park": "올림픽공원",
    "Yangjae Citizen's Forest": "양재시민의숲",
    "Pangyo": "판교",
    "Jeongja": "정자",
    "Dongcheon": "동천",
    "Suji District Office": "수지구청",
    "Gwanggyo": "광교",
    "Gwanggyo Jungang": "광교중앙",
    "Hyochang Park": "효창공원앞",
    "Oksu": "옥수",
    "Susaek": "수색",
    "Ilsan": "일산",
    "Paju": "파주",
    "Incheon Airport T1": "인천공항1터미널",
    "Incheon Airport": "인천공항1터미널",
    "ICN Airport": "인천공항1터미널",
    "ICN T1": "인천공항1터미널",
    "Incheon Airport T2": "인천공항2터미널",
    "ICN T2": "인천공항2터미널",
    "Cheongna Int'l City": "청라국제도시",
    "Seonjeongneung": "선정릉",
    "Migeum": "미금",
    "Ori": "오리",
    "Jukjeon": "죽전",
    "Kangnam": "강남",
    "Shinchon": "신촌",
    "Shinsa": "신사",
    "Kondae": "건대입구",
    "Edae": "이대",
    "Sodae": "서울대입구",
    "Godae": "고려대",
    "Yondae": "신촌",
    "Garosugil": "신사",
    "Garosu-gil": "신사",
    "Bukchon": "안국",
    "Bukchon Hanok Village": "안국",
    "Insadong": "안국",
    "Insa-dong": "안국",
    "Seoul Forest": "서울숲",
    "Seoul Forest Station": "서울숲",
    "Yeonnam-dong": "홍대입구",
    "Yeonnamdong": "홍대입구",
    "Mangwon": "망원",
    "Mangwon-dong": "망원",
    "Apgujeong Rodeo": "압구정로데오",
    "Apgujeong-Rodeo": "압구정로데오",
    "Sinyongsan": "신용산",
    "Eulji-ro": "을지로입구",
    "Jong-no": "종로3가",
    "Seongsu-dong": "성수",
    "Seongsudong": "성수",
    // Line 2 circular stations (missing)
    "Euljiro 4-ga": "을지로4가",
    "Sindang": "신당",
    "Sangwangsimni": "상왕십리",
    "Hanyang Univ.": "한양대",
    "Hanyang University": "한양대",
    "Guui": "구의",
    "Jamsil Naru": "잠실나루",
    "Jamsilnaru": "잠실나루",
    "Jamsil Saenae": "잠실새내",
    "Seocho": "서초",
    "Bangbae": "방배",
    "Bongcheon": "봉천",
    "Sillim": "신림",
    "Sindaebang": "신대방",
    "Daelim": "대림",
    "Yeongdeungpo-gu Office": "영등포구청",
    "Ahyeon": "아현",
    // Line 1 stations
    "Jongno 3(sam)-ga": "종로3가",
    "Jongno 5(o)-ga": "종로5가",
    "Dongmyo": "동묘앞",
    "Sinseol-dong": "신설동",
    "Sinseoldong": "신설동",
    "Jegi-dong": "제기동",
    "Jegidong": "제기동",
    // Line 3 stations
    "Ogeum": "오금",
    "Daecheong": "대청",
    "Suseo": "수서",
    "Irwon": "일원",
    "Daechi": "대치",
    "Jamwon": "잠원",
    // Line 4 stations
    "Sungshin Women's Univ.": "성신여대입구",
    "Sungshin Univ.": "성신여대입구",
    "Changdong": "창동",
    "Nowon": "노원",
    "Danggogae": "당고개",
    // Line 5 stations
    "Gonghang Market": "공항시장",
    "Gimpo International Airport": "김포공항",
    // Line 6 stations
    "Hangangjin": "한강진",
    "Ssangmun": "쌍문",
    // Line 8 stations
    "Songpa": "송파",
    "Garak Market": "가락시장"
  } as Record<string, string>,
  koreanToEnglish: {
    "서울역": "Seoul Station",
    "시청": "City Hall",
    "종각": "Jonggak",
    "종로3가": "Jongno 3-ga",
    "종로5가": "Jongno 5-ga",
    "동대문": "Dongdaemun",
    "청량리": "Cheongnyangni",
    "용산": "Yongsan",
    "노량진": "Noryangjin",
    "영등포": "Yeongdeungpo",
    "구로": "Guro",
    "인천": "Incheon",
    "부평": "Bupyeong",
    "수원": "Suwon",
    "강남": "Gangnam",
    "역삼": "Yeoksam",
    "삼성": "Samseong",
    "잠실": "Jamsil",
    "신도림": "Sindorim",
    "홍대입구": "Hongdae (Hongik Univ.)",
    "합정": "Hapjeong",
    "당산": "Dangsan",
    "여의도": "Yeouido",
    "건대입구": "Konkuk Univ.",
    "선릉": "Seolleung",
    "종합운동장": "Sports Complex",
    "강변": "Gangbyeon",
    "뚝섬": "Ttukseom",
    "성수": "Seongsu",
    "왕십리": "Wangsimni",
    "을지로3가": "Euljiro 3-ga",
    "을지로입구": "Euljiro 1-ga",
    "충정로": "Chungjeongno",
    "이대": "Ewha Womans Univ.",
    "신촌": "Sinchon",
    "사당": "Sadang",
    "낙성대": "Nakseongdae",
    "서울대입구": "Seoul Nat'l Univ.",
    "구로디지털단지": "Guro Digital Complex",
    "문래": "Mullae",
    "경복궁": "Gyeongbokgung",
    "안국": "Anguk",
    "충무로": "Chungmuro",
    "동대입구": "Dongguk Univ.",
    "약수": "Yaksu",
    "압구정": "Apgujeong",
    "신사": "Sinsa",
    "고속터미널": "Express Bus Terminal",
    "교대": "Gyodae",
    "남부터미널": "Nambu Bus Terminal",
    "양재": "Yangjae",
    "대화": "Daehwa",
    "주엽": "Juyeop",
    "명동": "Myeongdong",
    "회현": "Hoehyeon",
    "숙대입구": "Sookmyung Women's Univ.",
    "동대문역사문화공원": "Dongdaemun History & Culture Park",
    "혜화": "Hyehwa",
    "한성대입구": "Hansung Univ.",
    "미아": "Mia",
    "미아사거리": "Mia Sageori",
    "길음": "Gireum",
    "총신대입구": "Chongshin Univ.",
    "광화문": "Gwanghwamun",
    "청구": "Cheonggu",
    "행당": "Haengdang",
    "여의나루": "Yeouinaru",
    "마포": "Mapo",
    "공덕": "Gongdeok",
    "김포공항": "Gimpo Airport",
    "방화": "Banghwa",
    "이태원": "Itaewon",
    "삼각지": "Samgakji",
    "녹사평": "Noksapyeong",
    "한강진": "Hangang",
    "상수": "Sangsu",
    "월드컵경기장": "World Cup Stadium",
    "디지털미디어시티": "Digital Media City",
    "강남구청": "Gangnam-gu Office",
    "청담": "Cheongdam",
    "어린이대공원": "Children's Grand Park",
    "중곡": "Junggok",
    "뚝섬유원지": "Ttukseom Resort",
    "논현": "Nonhyeon",
    "학동": "Hakdong",
    "보광": "Bogwang",
    "장암": "Jangam",
    "도봉산": "Dobongsan",
    "몽촌토성": "Mongchontoseong",
    "강동구청": "Gangdong-gu Office",
    "천호": "Cheonho",
    "복정": "Bokjeong",
    "산성": "Sanseong",
    "모란": "Moran",
    "암사": "Amsa",
    "신논현": "Sinnonhyeon",
    "동작": "Dongjak",
    "국회의사당": "National Assembly",
    "염창": "Yeomchang",
    "개화": "Gaehwa",
    "올림픽공원": "Olympic Park",
    "양재시민의숲": "Yangjae Citizen's Forest",
    "판교": "Pangyo",
    "정자": "Jeongja",
    "동천": "Dongcheon",
    "수지구청": "Suji District Office",
    "광교": "Gwanggyo",
    "광교중앙": "Gwanggyo Jungang",
    "효창공원앞": "Hyochang Park",
    "옥수": "Oksu",
    "수색": "Susaek",
    "일산": "Ilsan",
    "파주": "Paju",
    "인천공항1터미널": "Incheon Airport T1",
    "인천공항2터미널": "Incheon Airport T2",
    "청라국제도시": "Cheongna Int'l City",
    "선정릉": "Seonjeongneung",
    "미금": "Migeum",
    "오리": "Ori",
    "죽전": "Jukjeon",
    "서울숲": "Seoul Forest",
    "망원": "Mangwon",
    "신용산": "Sinyongsan",
    "압구정로데오": "Apgujeong Rodeo",
    "고려대": "Korea University",
    // Line 2 circular stations
    "을지로4가": "Euljiro 4-ga",
    "신당": "Sindang",
    "상왕십리": "Sangwangsimni",
    "한양대": "Hanyang Univ.",
    "구의": "Guui",
    "잠실나루": "Jamsil Naru",
    "잠실새내": "Jamsil Saenae",
    "서초": "Seocho",
    "방배": "Bangbae",
    "봉천": "Bongcheon",
    "신림": "Sillim",
    "신대방": "Sindaebang",
    "대림": "Daelim",
    "영등포구청": "Yeongdeungpo-gu Office",
    "아현": "Ahyeon",
    // Line 1 stations
    "동묘앞": "Dongmyo",
    "신설동": "Sinseol-dong",
    "제기동": "Jegi-dong",
    // Line 3 stations
    "오금": "Ogeum",
    "대청": "Daecheong",
    "수서": "Suseo",
    "일원": "Irwon",
    "대치": "Daechi",
    "잠원": "Jamwon",
    // Line 4 stations
    "성신여대입구": "Sungshin Women's Univ.",
    "창동": "Changdong",
    "노원": "Nowon",
    "당고개": "Danggogae",
    // Line 5 stations
    "공항시장": "Gonghang Market",
    // Line 6 stations
    "쌍문": "Ssangmun",
    // Line 8 stations
    "송파": "Songpa",
    "가락시장": "Garak Market"
  } as Record<string, string>
};

export default stationNames;
